#! /bin/bash

ROOT_DIR=$(cd `dirname -- $0` && cd .. && pwd)

VENV_PATH=$(util/venv -p)

rm -rf \
    $VENV_PATH \
    .pytest_cache default/__pycache__ \
    default/lib \
    web/node_modules web/build web/coverage \

find . -name \*.pyc -delete
