#!/usr/bin/env python2

from os import path
from __init__ import CONFIG, UTIL, ROOT, CallTask, CallTaskRunner, VENV


VENV_PIP2 = path.join(VENV.path, 'bin', 'pip2')

# Check if server folder exists
if not path.exists(CONFIG.SERVER_PATH):
    CallTask(ROOT, [
        "svn", "export",
        "https://github.com/GoogleCloudPlatform/python-docs-samples" +
        "/trunk/appengine/standard/flask/tutorial", CONFIG.SERVER_PATH
    ]).run()

if not path.exists(CONFIG.WEB_PATH):
    CallTask(ROOT, ["npx", "create-react-app", CONFIG.WEB_PATH]).run()

tasks = [
    CallTask(CONFIG.WEB_PATH, ["yarn"]),
    CallTask(CONFIG.SERVER_PATH, [
        VENV_PIP2,
        "install",
        "-t",
        "lib",
        "-r",
        "requirements.txt",
        "--disable-pip-version-check",
        "-q",
    ])
]

CallTaskRunner.run(tasks)
