#!/usr/bin/env python2

from os import path
from _manage import ROOT, CallTask, CallTaskRunner, venv

v = venv()
VENV_PIP2 = path.join(v.path, 'bin', 'pip2')

batches = [
    [
        CallTask(ROOT, ["./_dependencies"]),
        CallTask(
            ROOT,
            [VENV_PIP2, "install", "gcp-devrel-py-tools", "mock", "pytest"]),
        #  Install /default dependencies into our environment for pytest
        CallTask(
            path.join(ROOT, "default"),
            [VENV_PIP2, "install", "-r", "requirements.txt"])
    ],
    [
        CallTask(ROOT, [path.join(v.path, 'bin', 'pytest')]),
        CallTask(path.join(ROOT, 'web'), ["CI=true", "yarn", "test"]),
    ]
]

for tasks in batches:
    CallTaskRunner.run(tasks)
